package com.example.geeknews.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.geeknews.bean.CollectionDbBean;

import com.example.geeknews.dao.CollectionDbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionDbBeanDaoConfig;

    private final CollectionDbBeanDao collectionDbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionDbBeanDaoConfig = daoConfigMap.get(CollectionDbBeanDao.class).clone();
        collectionDbBeanDaoConfig.initIdentityScope(type);

        collectionDbBeanDao = new CollectionDbBeanDao(collectionDbBeanDaoConfig, this);

        registerDao(CollectionDbBean.class, collectionDbBeanDao);
    }
    
    public void clear() {
        collectionDbBeanDaoConfig.clearIdentityScope();
    }

    public CollectionDbBeanDao getCollectionDbBeanDao() {
        return collectionDbBeanDao;
    }

}
